version: "3.9"
services:
  site_bravion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site_bravion
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true

      - traefik.http.routers.bravion_http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.bravion_http.entrypoints=web
      - traefik.http.routers.bravion_http.middlewares=bravion_redirect_https
      - traefik.http.middlewares.bravion_redirect_https.redirectscheme.scheme=https
      - traefik.http.middlewares.bravion_redirect_https.redirectscheme.permanent=true

      - traefik.http.routers.bravion_https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      - traefik.http.routers.bravion_https.entrypoints=websecure
      - traefik.http.routers.bravion_https.tls=true
      - traefik.http.routers.bravion_https.tls.certresolver=${CERT_RESOLVER}

      - traefik.http.services.bravion.loadbalancer.server.port=80

networks:
  traefik_proxy:
    external: true
    name: ${TRAEFIK_NETWORK}
